const mongoose = require('mongoose');
const {Schema} = mongoose;

const ActorSchema = new Schema({
    id: {
        type: String,
        required: true},
    type: {
        type: String,
        required: true},
    login: {
        type: String,
        required: true},
    avatar_url: {
        type: String,
        required: true},
    __updated_at: {
        type: Date,
        required: false},
    bio: {
        type: String,
        required: false},
    company: {
        type: String,
        required: false},
    created_at: {
        type: Date,
        required: false},
    database_id: {
        type: Number,
        required: false},
    email: {
        type: String,
        required: false},
    followers: {
        type: Number,
        required: false},
    following: {
        type: Number,
        required: false},
    gists: {
        type: Number,
        required: false},
    is_bounty_hunter: {
        type: Boolean,
        required: false},
    is_campus_expert: {
        type: Boolean,
        required: false},
    is_developer_program_member: {
        type: Boolean,
        required: false},
    is_employee: {
        type: Boolean,
        required: false},
    is_hireable: {
        type: Boolean,
        required: false},
    is_site_admin: {
        type: Boolean,
        required: false},
    location: {
        type: String,
        required: false},
    name: {
        type: String,
        required: false},
    projects: {
        type: Number,
        required: false},
    projects_url: {
        type: String,
        required: false},
    repositories: {
        type: Number,
        required: false},
    repositories_contributed_to: {
        type: Number,
        required: false},
    starred_repositories: {
        type: Number,
        required: false},
    status: {
        type: String,
        required: false},
    twitter_username: {
        type: String,
        required: false},
    updated_at: {
        type: Date,
        required: false},
    watching: {
        type: Number,
        required: false},
    website_url: {
        type: String,
        required: false},
    description: {
        type: String,
        required: false},
    is_verified: {
        type: Boolean,
        required: false},
    members_with_role: {
        type: Number,
        required: false},
    teams: {
        type: Number,
        required: false},
    user: {
        type: String,
        required: false},
});

const Actor = mongoose.model("Actor", ActorSchema);

module.exports = Actor;